### ISSUE TITLE
Failed to get available operating systems: VPS with name 'x' not found

### ISSUE THREAD

**Issue by Anthirian** [aequitas/terraform-provider-transip#74] opened 2023-12-18 13:38 UTC
Since today I'm seeing errors creating a `transip_vps` resource using this provider. The error message is below.

```
module.frontend.transip_vps.frontends["description"]: Creating...
╷
│ Error: Failed to get available operating systems: VPS with name 'x' not found
│
│   with module.frontend.transip_vps.frontends["description"],
│   on frontend/frontends.tf line 1, in resource "transip_vps" "frontends":
│    1: resource "transip_vps" "frontends" {
│
```

The `frontends.tf` file looks like this:

```tf
resource "transip_vps" "frontends" {
  for_each         = var.frontend_suffixes
  description      = "${var.codename}-${each.key}"
  install_text     = file("${path.module}/user-data.yml")
  install_flavour  = "cloudinit"
  product_name     = "vps-bladevps-x4"
  operating_system = "ubuntu-20.04"
}
```

I suspect TransIP has modified their API slightly and this particular code seems to be erroring now.

https://github.com/aequitas/terraform-provider-transip/blob/791c8d0db2f511b9bdfc4d982e7c83883a97b0a2/resource_transip_vps.go#L173-L177

**Comment by StanvanHoorn** [comment] 2023-12-18 13:51
We also are experiencing this issue. Tried both version 0.1.20 and 0.1.19 of the provider, so I also suspect a change in the Transip API to be the cause.

**Comment by aequitas** [comment] 2023-12-18 16:26
I'm currently pushing a build that removes the OS check before creating a VPS, this is a stopgap measure until the proper solution made by @JoooostB can be merged: https://github.com/aequitas/terraform-provider-transip/pull/75

The release should be ready in a few minutes.

**Comment by fvanmaldegem** [comment] 2023-12-18 16:29
The problem where the `vpsName` in the GET call to `/v6/vps/{vpsName}/operating-systems` must be an existing VPS have now been resolved in the TransIP API.

**Comment by aequitas** [comment] 2023-12-18 17:05
@fvanmaldegem great, I'll revert the hotfix. Do I understand correctly that querying with a non-existing VPS name is a supported method, or will that change in the future?

**Comment by fvanmaldegem** [comment] 2023-12-18 18:03
@aequitas We will keep this for backward compatibility and do not suspect to make any changes to this functionality in the future.

**Closed** 2023-12-18 18:33 UTC
